dist: xenial
sudo: require
language: cpp
os: linux
compiler:
  - gcc
script:
    - g++ -std=c++11 -coverage -Isrc -Iinclude test/main.cpp -o textable_test
    - ./textable_test
after_success:
  - bash <(curl -s https://codecov.io/bash)
