dist: xenial
sudo: require
language: cpp
compiler:
  - gcc
script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ./textable_test
after_success:
  - bash <(curl -s https://codecov.io/bash)
