# version string format
version: "{build}"

image: Visual Studio 2017

# clone directory
clone_folder: C:\projects\textable

init:
    - git config --global core.autocrlf input

# branches to build
branches:
    # whitelist
    only:
        - master

platform:
    - Win32
    - x64

# build Configurations, i.e. Debug, Release, etc.
configuration:
    - Debug
    - Release

build_script:
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
    - cd C:\projects\textable
    - mkdir build
    - cd build
    - cmake .. -G "NMake Makefiles"
    - nmake

test_script:
    - cd C:\projects\textable\build
    - ctest -VV
